// Datos de ubicaciones para países y sus subdivisiones
export const countries: { label: string; value: string }[] = [
  { label: 'México', value: 'México' },
  { label: 'Estados Unidos', value: 'Estados Unidos' },
  { label: 'Canadá', value: 'Canadá' },
  { label: 'España', value: 'España' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Chile', value: 'Chile' },
  { label: 'Perú', value: 'Perú' },
  { label: 'Brasil', value: 'Brasil' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Panamá', value: 'Panamá' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Belice', value: 'Belice' },
];

export const states: Record<string, { label: string; value: string }[]> = {
  México: [
    { label: 'Aguascalientes', value: 'Aguascalientes' },
    { label: 'Baja California', value: 'Baja California' },
    { label: 'Baja California Sur', value: 'Baja California Sur' },
    { label: 'Campeche', value: 'Campeche' },
    { label: 'Chiapas', value: 'Chiapas' },
    { label: 'Chihuahua', value: 'Chihuahua' },
    { label: 'Coahuila', value: 'Coahuila' },
    { label: 'Colima', value: 'Colima' },
    { label: 'Ciudad de México', value: 'Ciudad de México' },
    { label: 'Durango', value: 'Durango' },
    { label: 'Guanajuato', value: 'Guanajuato' },
    { label: 'Guerrero', value: 'Guerrero' },
    { label: 'Hidalgo', value: 'Hidalgo' },
    { label: 'Jalisco', value: 'Jalisco' },
    { label: 'México', value: 'México' },
    { label: 'Michoacán', value: 'Michoacán' },
    { label: 'Morelos', value: 'Morelos' },
    { label: 'Nayarit', value: 'Nayarit' },
    { label: 'Nuevo León', value: 'Nuevo León' },
    { label: 'Oaxaca', value: 'Oaxaca' },
    { label: 'Puebla', value: 'Puebla' },
    { label: 'Querétaro', value: 'Querétaro' },
    { label: 'Quintana Roo', value: 'Quintana Roo' },
    { label: 'San Luis Potosí', value: 'San Luis Potosí' },
    { label: 'Sinaloa', value: 'Sinaloa' },
    { label: 'Sonora', value: 'Sonora' },
    { label: 'Tabasco', value: 'Tabasco' },
    { label: 'Tamaulipas', value: 'Tamaulipas' },
    { label: 'Tlaxcala', value: 'Tlaxcala' },
    { label: 'Veracruz', value: 'Veracruz' },
    { label: 'Yucatán', value: 'Yucatán' },
    { label: 'Zacatecas', value: 'Zacatecas' },
  ],
  'Estados Unidos': [
    { label: 'California', value: 'California' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Florida', value: 'Florida' },
    { label: 'Nueva York', value: 'Nueva York' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Pensilvania', value: 'Pensilvania' },
    { label: 'Ohio', value: 'Ohio' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Carolina del Norte', value: 'Carolina del Norte' },
    { label: 'Michigan', value: 'Michigan' },
  ],
  Canadá: [
    { label: 'Ontario', value: 'Ontario' },
    { label: 'Quebec', value: 'Quebec' },
    { label: 'Columbia Británica', value: 'Columbia Británica' },
    { label: 'Alberta', value: 'Alberta' },
    { label: 'Manitoba', value: 'Manitoba' },
    { label: 'Saskatchewan', value: 'Saskatchewan' },
    { label: 'Nueva Escocia', value: 'Nueva Escocia' },
    { label: 'Nuevo Brunswick', value: 'Nuevo Brunswick' },
    { label: 'Isla del Príncipe Eduardo', value: 'Isla del Príncipe Eduardo' },
    { label: 'Terranova y Labrador', value: 'Terranova y Labrador' },
  ],
  España: [
    { label: 'Madrid', value: 'Madrid' },
    { label: 'Cataluña', value: 'Cataluña' },
    { label: 'Andalucía', value: 'Andalucía' },
    { label: 'Valencia', value: 'Valencia' },
    { label: 'Galicia', value: 'Galicia' },
    { label: 'Castilla y León', value: 'Castilla y León' },
    { label: 'País Vasco', value: 'País Vasco' },
    { label: 'Castilla-La Mancha', value: 'Castilla-La Mancha' },
    { label: 'Canarias', value: 'Canarias' },
    { label: 'Aragón', value: 'Aragón' },
  ],
  Argentina: [
    { label: 'Buenos Aires', value: 'Buenos Aires' },
    { label: 'Córdoba', value: 'Córdoba' },
    { label: 'Santa Fe', value: 'Santa Fe' },
    { label: 'Mendoza', value: 'Mendoza' },
    { label: 'Tucumán', value: 'Tucumán' },
    { label: 'Entre Ríos', value: 'Entre Ríos' },
    { label: 'Salta', value: 'Salta' },
    { label: 'Chaco', value: 'Chaco' },
    { label: 'Corrientes', value: 'Corrientes' },
    { label: 'Misiones', value: 'Misiones' },
  ],
  Colombia: [
    { label: 'Bogotá', value: 'Bogotá' },
    { label: 'Antioquia', value: 'Antioquia' },
    { label: 'Valle del Cauca', value: 'Valle del Cauca' },
    { label: 'Cundinamarca', value: 'Cundinamarca' },
    { label: 'Atlántico', value: 'Atlántico' },
    { label: 'Santander', value: 'Santander' },
    { label: 'Norte de Santander', value: 'Norte de Santander' },
    { label: 'Bolívar', value: 'Bolívar' },
    { label: 'Córdoba', value: 'Córdoba' },
    { label: 'Tolima', value: 'Tolima' },
  ],
  Chile: [
    { label: 'Santiago', value: 'Santiago' },
    { label: 'Valparaíso', value: 'Valparaíso' },
    { label: 'Biobío', value: 'Biobío' },
    { label: 'Maule', value: 'Maule' },
    { label: 'O\'Higgins', value: 'O\'Higgins' },
    { label: 'Coquimbo', value: 'Coquimbo' },
    { label: 'Araucanía', value: 'Araucanía' },
    { label: 'Los Lagos', value: 'Los Lagos' },
    { label: 'Tarapacá', value: 'Tarapacá' },
    { label: 'Antofagasta', value: 'Antofagasta' },
  ],
  Perú: [
    { label: 'Lima', value: 'Lima' },
    { label: 'Arequipa', value: 'Arequipa' },
    { label: 'Cusco', value: 'Cusco' },
    { label: 'La Libertad', value: 'La Libertad' },
    { label: 'Piura', value: 'Piura' },
    { label: 'Lambayeque', value: 'Lambayeque' },
    { label: 'Junín', value: 'Junín' },
    { label: 'Puno', value: 'Puno' },
    { label: 'Callao', value: 'Callao' },
    { label: 'Ica', value: 'Ica' },
  ],
  Brasil: [
    { label: 'São Paulo', value: 'São Paulo' },
    { label: 'Río de Janeiro', value: 'Río de Janeiro' },
    { label: 'Minas Gerais', value: 'Minas Gerais' },
    { label: 'Bahía', value: 'Bahía' },
    { label: 'Paraná', value: 'Paraná' },
    { label: 'Rio Grande do Sul', value: 'Rio Grande do Sul' },
    { label: 'Pernambuco', value: 'Pernambuco' },
    { label: 'Ceará', value: 'Ceará' },
    { label: 'Pará', value: 'Pará' },
    { label: 'Santa Catarina', value: 'Santa Catarina' },
  ],
  Venezuela: [
    { label: 'Caracas', value: 'Caracas' },
    { label: 'Miranda', value: 'Miranda' },
    { label: 'Zulia', value: 'Zulia' },
    { label: 'Táchira', value: 'Táchira' },
    { label: 'Anzoátegui', value: 'Anzoátegui' },
    { label: 'Bolívar', value: 'Bolívar' },
    { label: 'Carabobo', value: 'Carabobo' },
    { label: 'Lara', value: 'Lara' },
    { label: 'Sucre', value: 'Sucre' },
    { label: 'Monagas', value: 'Monagas' },
  ],
  Ecuador: [
    { label: 'Pichincha', value: 'Pichincha' },
    { label: 'Guayas', value: 'Guayas' },
    { label: 'Azuay', value: 'Azuay' },
    { label: 'Manabí', value: 'Manabí' },
    { label: 'Santo Domingo de los Tsáchilas', value: 'Santo Domingo de los Tsáchilas' },
    { label: 'El Oro', value: 'El Oro' },
    { label: 'Los Ríos', value: 'Los Ríos' },
    { label: 'Tungurahua', value: 'Tungurahua' },
    { label: 'Imbabura', value: 'Imbabura' },
    { label: 'Chimborazo', value: 'Chimborazo' },
  ],
  Uruguay: [
    { label: 'Montevideo', value: 'Montevideo' },
    { label: 'Canelones', value: 'Canelones' },
    { label: 'Maldonado', value: 'Maldonado' },
    { label: 'Salto', value: 'Salto' },
    { label: 'Paysandú', value: 'Paysandú' },
    { label: 'Río Negro', value: 'Río Negro' },
    { label: 'Tacuarembó', value: 'Tacuarembó' },
    { label: 'Cerro Largo', value: 'Cerro Largo' },
    { label: 'Rivera', value: 'Rivera' },
    { label: 'Artigas', value: 'Artigas' },
  ],
  Paraguay: [
    { label: 'Asunción', value: 'Asunción' },
    { label: 'Central', value: 'Central' },
    { label: 'Alto Paraná', value: 'Alto Paraná' },
    { label: 'Itapúa', value: 'Itapúa' },
    { label: 'Caaguazú', value: 'Caaguazú' },
    { label: 'Paraguarí', value: 'Paraguarí' },
    { label: 'Misiones', value: 'Misiones' },
    { label: 'Ñeembucú', value: 'Ñeembucú' },
    { label: 'Amambay', value: 'Amambay' },
    { label: 'Canindeyú', value: 'Canindeyú' },
  ],
  Bolivia: [
    { label: 'La Paz', value: 'La Paz' },
    { label: 'Santa Cruz', value: 'Santa Cruz' },
    { label: 'Cochabamba', value: 'Cochabamba' },
    { label: 'Potosí', value: 'Potosí' },
    { label: 'Chuquisaca', value: 'Chuquisaca' },
    { label: 'Oruro', value: 'Oruro' },
    { label: 'Tarija', value: 'Tarija' },
    { label: 'Beni', value: 'Beni' },
    { label: 'Pando', value: 'Pando' },
  ],
  Panamá: [
    { label: 'Panamá', value: 'Panamá' },
    { label: 'Colón', value: 'Colón' },
    { label: 'Chiriquí', value: 'Chiriquí' },
    { label: 'Veraguas', value: 'Veraguas' },
    { label: 'Herrera', value: 'Herrera' },
    { label: 'Los Santos', value: 'Los Santos' },
    { label: 'Coclé', value: 'Coclé' },
    { label: 'Darién', value: 'Darién' },
    { label: 'Bocas del Toro', value: 'Bocas del Toro' },
    { label: 'Guna Yala', value: 'Guna Yala' },
  ],
  'Costa Rica': [
    { label: 'San José', value: 'San José' },
    { label: 'Alajuela', value: 'Alajuela' },
    { label: 'Cartago', value: 'Cartago' },
    { label: 'Heredia', value: 'Heredia' },
    { label: 'Guanacaste', value: 'Guanacaste' },
    { label: 'Puntarenas', value: 'Puntarenas' },
    { label: 'Limón', value: 'Limón' },
  ],
  Nicaragua: [
    { label: 'Managua', value: 'Managua' },
    { label: 'León', value: 'León' },
    { label: 'Granada', value: 'Granada' },
    { label: 'Masaya', value: 'Masaya' },
    { label: 'Chinandega', value: 'Chinandega' },
    { label: 'Matagalpa', value: 'Matagalpa' },
    { label: 'Estelí', value: 'Estelí' },
    { label: 'Carazo', value: 'Carazo' },
    { label: 'Chontales', value: 'Chontales' },
    { label: 'Rivas', value: 'Rivas' },
  ],
  Honduras: [
    { label: 'Francisco Morazán', value: 'Francisco Morazán' },
    { label: 'Cortés', value: 'Cortés' },
    { label: 'Atlántida', value: 'Atlántida' },
    { label: 'Yoro', value: 'Yoro' },
    { label: 'Colón', value: 'Colón' },
    { label: 'Olancho', value: 'Olancho' },
    { label: 'Santa Bárbara', value: 'Santa Bárbara' },
    { label: 'Copán', value: 'Copán' },
    { label: 'Ocotepeque', value: 'Ocotepeque' },
    { label: 'Lempira', value: 'Lempira' },
  ],
  'El Salvador': [
    { label: 'San Salvador', value: 'San Salvador' },
    { label: 'La Libertad', value: 'La Libertad' },
    { label: 'Santa Ana', value: 'Santa Ana' },
    { label: 'Sonsonate', value: 'Sonsonate' },
    { label: 'Usulután', value: 'Usulután' },
    { label: 'San Miguel', value: 'San Miguel' },
    { label: 'Morazán', value: 'Morazán' },
    { label: 'La Unión', value: 'La Unión' },
    { label: 'Cuscatlán', value: 'Cuscatlán' },
    { label: 'Chalatenango', value: 'Chalatenango' },
  ],
  Guatemala: [
    { label: 'Guatemala', value: 'Guatemala' },
    { label: 'Quetzaltenango', value: 'Quetzaltenango' },
    { label: 'Alta Verapaz', value: 'Alta Verapaz' },
    { label: 'Huehuetenango', value: 'Huehuetenango' },
    { label: 'San Marcos', value: 'San Marcos' },
    { label: 'Escuintla', value: 'Escuintla' },
    { label: 'Chimaltenango', value: 'Chimaltenango' },
    { label: 'Sacatepéquez', value: 'Sacatepéquez' },
    { label: 'Totonicapán', value: 'Totonicapán' },
    { label: 'Sololá', value: 'Sololá' },
  ],
  Belice: [
    { label: 'Belice', value: 'Belice' },
    { label: 'Cayo', value: 'Cayo' },
    { label: 'Corozal', value: 'Corozal' },
    { label: 'Orange Walk', value: 'Orange Walk' },
    { label: 'Stann Creek', value: 'Stann Creek' },
    { label: 'Toledo', value: 'Toledo' },
  ],
};

export const cities: Record<string, { label: string; value: string }[]> = {
  // Ejemplo para algunos estados, agregar más según necesidad
  'Ciudad de México': [
    { label: 'Centro Histórico', value: 'Centro Histórico' },
    { label: 'Polanco', value: 'Polanco' },
    { label: 'Roma', value: 'Roma' },
    // Agregar más
  ],
  Jalisco: [
    { label: 'Guadalajara', value: 'Guadalajara' },
    { label: 'Zapopan', value: 'Zapopan' },
    { label: 'Tlaquepaque', value: 'Tlaquepaque' },
  ],
  // Estados Unidos
  California: [
    { label: 'Los Ángeles', value: 'Los Ángeles' },
    { label: 'San Francisco', value: 'San Francisco' },
    { label: 'San Diego', value: 'San Diego' },
    { label: 'Sacramento', value: 'Sacramento' },
  ],
  Texas: [
    { label: 'Houston', value: 'Houston' },
    { label: 'Dallas', value: 'Dallas' },
    { label: 'Austin', value: 'Austin' },
    { label: 'San Antonio', value: 'San Antonio' },
  ],
  Florida: [
    { label: 'Miami', value: 'Miami' },
    { label: 'Orlando', value: 'Orlando' },
    { label: 'Tampa', value: 'Tampa' },
    { label: 'Jacksonville', value: 'Jacksonville' },
  ],
  // España
  Madrid: [
    { label: 'Madrid Centro', value: 'Madrid Centro' },
    { label: 'Chamartín', value: 'Chamartín' },
    { label: 'Retiro', value: 'Retiro' },
  ],
  Cataluña: [
    { label: 'Barcelona', value: 'Barcelona' },
    { label: 'Girona', value: 'Girona' },
    { label: 'Tarragona', value: 'Tarragona' },
  ],
  Andalucía: [
    { label: 'Sevilla', value: 'Sevilla' },
    { label: 'Málaga', value: 'Málaga' },
    { label: 'Granada', value: 'Granada' },
  ],
  // Argentina
  'Buenos Aires': [
    { label: 'Buenos Aires Centro', value: 'Buenos Aires Centro' },
    { label: 'Palermo', value: 'Palermo' },
    { label: 'Recoleta', value: 'Recoleta' },
  ],
  Córdoba: [
    { label: 'Córdoba Capital', value: 'Córdoba Capital' },
    { label: 'Villa Carlos Paz', value: 'Villa Carlos Paz' },
  ],
  // Colombia
  Bogotá: [
    { label: 'Centro', value: 'Centro' },
    { label: 'Chapinero', value: 'Chapinero' },
    { label: 'Usaquén', value: 'Usaquén' },
  ],
  Antioquia: [
    { label: 'Medellín', value: 'Medellín' },
    { label: 'Envigado', value: 'Envigado' },
  ],
  // Agregar para otros estados
};